### ISSUE TITLE
Deepspeed zero3 error: "expected all tensored to be on the same device"

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#1698] opened 2024-06-08 14:04 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Deepspeed zero3 should work out of the box.

### Current behaviour

Error:
```
[rank1]:     self.unscale_and_clip_grads(sub_group_id, scaled_global_grad_norm)
[rank1]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 2117, in unscale_and_clip_grads
[rank1]:     self.fp32_partitioned_groups_flat[sub_group_id].grad.mul_(1. / combined_scale)
[rank1]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
[rank3]: Traceback (most recent call last):
[rank3]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank3]:   File "<frozen runpy>", line 88, in _run_code
[rank3]:   File "/home/layla/src/axolotl/src/axolotl/cli/train.py", line 70, in <module>
[rank3]:     fire.Fire(do_cli)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
[rank3]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank3]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
[rank3]:     component, remaining_args = _CallAndUpdateTrace(
[rank3]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank3]:     component = fn(*varargs, **kwargs)
[rank3]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/src/axolotl/src/axolotl/cli/train.py", line 38, in do_cli
[rank3]:     return do_train(parsed_cfg, parsed_cli_args)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/src/axolotl/src/axolotl/cli/train.py", line 66, in do_train
[rank3]:     return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/src/axolotl/src/axolotl/train.py", line 170, in train
[rank3]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 1885, in train
[rank3]:     return inner_training_loop(
[rank3]:            ^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
[rank3]:     tr_loss_step = self.training_step(model, inputs)
[rank3]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3250, in training_step
[rank3]:     self.accelerator.backward(loss)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 2117, in backward
[rank3]:     self.deepspeed_engine_wrapped.backward(loss, **kwargs)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 175, in backward
[rank3]:     self.engine.step()
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2169, in step
[rank3]:     self._take_model_step(lr_kwargs)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
[rank3]:     self.optimizer.step()
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank3]:     ret_val = func(*args, **kwargs)
[rank3]:               ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 2047, in step
[rank3]:     self.unscale_and_clip_grads(sub_group_id, scaled_global_grad_norm)
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank3]:     ret_val = func(*args, **kwargs)
[rank3]:               ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 2117, in unscale_and_clip_grads
[rank3]:     self.fp32_partitioned_groups_flat[sub_group_id].grad.mul_(1. / combined_scale)
[rank3]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cpu!
```

### Steps to reproduce

1. Use latest master branch
2. Train using deepspeed zero3 config

### Config yaml

```yaml
base_model: models/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: train.jsonl
    ds_type: json # see other options below
    type: sharegpt
    conversation: chatml
    roles:
      input: ['User', 'Information']
      output: ['Layla']

chat_template: chatml
default_system_message: The following is a conversation. Embody the character and personality completely.

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-7

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: false
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 5
evals_per_epoch: 10
eval_table_size:
saves_per_epoch: 10
debug:
deepspeed: deepspeed_configs/zero3_bf16_cpuoffload_all.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
tokens: # these are delimiters
  - "<|im_start|>"
  - "<|im_end|>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment] 2024-06-08 14:08
Can you try with the optimizer set to adamw_bnb_8bit instead of the paged optimizer?

**Comment by l3utterfly** [comment] 2024-06-08 14:14
I just tried that, still getting the same issue.

**Comment by winglian** [comment] 2024-06-08 15:02
okay, I was able to reproduce both cases on my setup. I was able to get it working using cpuoffload_params rather than offloading all. 

@muellerzr, I vaguely remember this working at some point, any known changes to accelerate that might cause the total_norm  in deepspeed to be on GPU and the `self.fp32_partitioned_groups_flat` dict to be on CPU?

```
    self.engine.step()                                                                                                                                                                            File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step                                                                              
    self._take_model_step(lr_kwargs)                                                                                                                                                            
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step                                                                  
    self.optimizer.step()                                                                                                                                                                       
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn                                                                              
    ret_val = func(*args, **kwargs)                                                                                                                                                             
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2047, in step                                                                         
    self.unscale_and_clip_grads(sub_group_id, scaled_global_grad_norm)                                                                                                                          
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn                                                                              
    ret_val = func(*args, **kwargs)                                                                                                                                                             
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2117, in unscale_and_clip_grads                                                       
    self.fp32_partitioned_groups_flat[sub_group_id].grad.mul_(1. / combined_scale)                                                                                                              
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!    
```

**Comment by winglian** [comment] 2024-06-08 15:18
@l3utterfly  looks like it's related to https://github.com/microsoft/DeepSpeed/pull/5461 

downgrading deepspeed to 0.14.1 didn't seem to help either. but was able to get it to work by `pip uninstall deepspeed` followed by installing it from source at the git sha of the merged fix: `pip install "deepspeed @ git+https://github.com/microsoft/DeepSpeed.git@bc48371c5e1fb8fd70fc79285e66201dbb65679b"`

**Comment by l3utterfly** [comment] 2024-06-08 15:20
Thank you, I will try this tomorrow!
________________________________

**Comment by l3utterfly** [comment] 2024-06-09 02:55
Thanks for the help! I got a little further after installing deepspeed to the specific version, now I am getting this error:

```
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire                                                                                       [45/1935]
[rank5]:     component, remaining_args = _CallAndUpdateTrace(
[rank5]:                                 ^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank5]:     component = fn(*varargs, **kwargs)
[rank5]:                 ^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/axolotl/src/axolotl/cli/train.py", line 38, in do_cli
[rank5]:     return do_train(parsed_cfg, parsed_cli_args)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/axolotl/src/axolotl/cli/train.py", line 66, in do_train
[rank5]:     return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/axolotl/src/axolotl/train.py", line 170, in train
[rank5]:     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 1885, in train
[rank5]:     return inner_training_loop(
[rank5]:            ^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
[rank5]:     tr_loss_step = self.training_step(model, inputs)
[rank5]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 3250, in training_step
[rank5]:     self.accelerator.backward(loss)
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/accelerator.py", line 2117, in backward
[rank5]:     self.deepspeed_engine_wrapped.backward(loss, **kwargs)
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/utils/deepspeed.py", line 175, in backward
[rank5]:     self.engine.step()
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2169, in step
[rank5]:     self._take_model_step(lr_kwargs)
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
[rank5]:     self.optimizer.step()
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank5]:     ret_val = func(*args, **kwargs)
[rank5]:               ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 2050, in step
[rank5]:     self._optimizer_step(sub_group_id)
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 939, in _optimizer_step
[rank5]:     cpu_loss = self.optimizer.step()
[rank5]:                ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/pytorch/torch/optim/lr_scheduler.py", line 129, in wrapper
[rank5]:     return func.__get__(opt, opt.__class__)(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/pytorch/torch/optim/optimizer.py", line 483, in wrapper
[rank5]:     out = func(*args, **kwargs)
[rank5]:           ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 287, in step
[rank5]:     self.update_step(group, p, gindex, pindex)
[rank5]:   File "/home/layla/src/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 542, in update_step
[rank5]:     F.optimizer_update_8bit_blockwise(
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1770, in optimizer_update_8bit_blockwise
[rank5]:     prev_device = pre_call(g.device)
[rank5]:                   ^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/bitsandbytes/functional.py", line 459, in pre_call
[rank5]:     torch.cuda.set_device(device)
[rank5]:   File "/home/layla/src/pytorch/torch/cuda/__init__.py", line 414, in set_device
[rank5]:     device = _get_device_index(device)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/layla/src/pytorch/torch/cuda/_utils.py", line 34, in _get_device_index
[rank5]:     raise ValueError(f"Expected a cuda device, but got: {device}")
[rank5]: ValueError: Expected a cuda device, but got: cpu
```

**Closed as completed** 2024-06-09 21:13 UTC
Labels: bug

**Comment by l3utterfly** [comment] 2024-06-10 02:15
@winglian Can you help with my last error please? I don't think this issue should be closed as I'm still unable to start training. Appreciate any help on this matter.
