### ISSUE TITLE
Fine tuned model not working in text generation inference hugging face

### ISSUE THREAD

**Issue by Stealthwriter** [axolotl-ai-cloud/axolotl#731] opened 2023-10-14 16:06 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I fined tuned mistral using Axolotl, it should work when I load it with TGI

### Current behaviour

I get the following error: 

2023-10-14T16:02:58.295849317Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
2023-10-14T16:02:58.295852237Z     server.serve(
2023-10-14T16:02:58.295854417Z 
2023-10-14T16:02:58.295856457Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
2023-10-14T16:02:58.295859537Z     asyncio.run(
2023-10-14T16:02:58.295862217Z 
2023-10-14T16:02:58.295864207Z   File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
2023-10-14T16:02:58.295866417Z     return loop.run_until_complete(main)
2023-10-14T16:02:58.295868557Z 
2023-10-14T16:02:58.295870517Z   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2023-10-14T16:02:58.295872697Z     return future.result()
2023-10-14T16:02:58.295875367Z 
2023-10-14T16:02:58.295877347Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
2023-10-14T16:02:58.295879417Z     model = get_model(
2023-10-14T16:02:58.295881567Z 
2023-10-14T16:02:58.295883647Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 252, in get_model
2023-10-14T16:02:58.295886137Z     return FlashMistral(
2023-10-14T16:02:58.295888297Z 
2023-10-14T16:02:58.295890277Z   File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_mistral.py", line 297, in __init__
2023-10-14T16:02:58.295892437Z     tokenizer = LlamaTokenizerFast.from_pretrained(
2023-10-14T16:02:58.295894887Z 
2023-10-14T16:02:58.295897487Z   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
2023-10-14T16:02:58.295938318Z     return cls._from_pretrained(
2023-10-14T16:02:58.295941208Z 
2023-10-14T16:02:58.295943218Z   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1886, in _from_pretrained
2023-10-14T16:02:58.295945328Z     slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
2023-10-14T16:02:58.295947648Z 
2023-10-14T16:02:58.295949598Z   File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
2023-10-14T16:02:58.295951718Z     raise ValueError(
2023-10-14T16:02:58.295953818Z 
2023-10-14T16:02:58.295955818Z ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.
2023-10-14T16:02:58.295958108Z  rank=0

### Steps to reproduce

Fine tune a mistral model, try to run it with TGI

### Config yaml

default mistral config, only changed epoc to 5, and dataset

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

latest

### axolotl branch-commit

latest

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by flexchar** [comment] 2023-10-15 12:45
1. How exactly did you upload the model to HuggingFace? 
2. And how exactly are you trying to load into TGI?

I fine tuned many using the tool and all are loading flawlessly into TGI. Perhaps I can help you out.

**Comment by Stealthwriter** [comment] 2023-10-15 12:48
I used hugging-face cli upload repo_id local path

I used run pod, and started TGI with the template (it works fine with all models I tried before)

**Comment by flexchar** [comment] 2023-10-15 14:25
Is there any difference in the files uploaded to what you typically have? Maybe something got lost.

**Comment by NanoCode012** [comment] 2023-10-22 16:22
Hello! Please try delete `<unk>` from your `added_tokens.json`. Please let me know if this fixed it!

Explanation: This was caused by some bugs in transformers, re-adding tokens. It should be fixed in newer version of transformers (v.4.34.1). You can pull latest main in axolotl, reinstall packages, and try retrain if you want.

**Comment by NanoCode012** [comment] 2023-10-31 06:16
Hello, may I ask if this problem is solved? If so, can we close this?

**Comment by flexchar** [comment] 2023-10-31 07:34
I actually tried a few days ago running TGI with tuned Mistral and I had the same error. However using AWQ quant of fine-tuned Mistral works flawlessly. I wonder that it may not be the issue of `axolotl` but rather TGI.

**Comment by NanoCode012** [comment] 2023-11-02 09:32
I'll close this since @Stealthwriter hasn't gotten back. For others with this issue, please see https://github.com/OpenAccess-AI-Collective/axolotl/issues/731#issuecomment-1774136068

**Closed as completed by NanoCode012** 2023-11-02 09:32 UTC
Labels: bug

**Comment by hahmad2008** [comment] 2023-12-29 19:07
@NanoCode012 @flexchar @Stealthwriter 
I used this configurations for special_tokens in fine-tuning:

```
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

but I got this error while loading the finetuned model.

`tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=use_fast)
`

Error:

> load_model
>   File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 736, in from_pretrained
>     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
>     return cls._from_pretrained(
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
>     raise ValueError(
> ValueError: Non-consecutive added token '<unk>' found. Should have index 32000 but has index 0 in saved vocabulary.


Is there any way to solve that?

**Comment by NanoCode012** [comment] 2023-12-30 06:27
@hahmad2008 , may I ask if this is from a recent commit? I believe this issue should've been fixed. Could you share your `tokenizer_config.json` and `special_tokens_map.json` and `added_tokens.json` if you have them? You might just need to hack the value of index 32000 to index 0

**Comment by ZQ-Dev8** [comment] 2024-01-22 21:48
@NanoCode012 this issue has popped up again, albeit with a different base model and error message: https://github.com/OpenAccess-AI-Collective/axolotl/issues/1165. Any attention would be greatly appreciated.
