### ISSUE TITLE
Installation on m2 macOS fails

### ISSUE THREAD

**Issue by wbharding** [axolotl-ai-cloud/axolotl#595] opened 2023-09-17 15:36 UTC
### What piece of documentation is affected?

Installation instructions within readme.md

### What part(s) of the article would you like to see updated?

The install instructions state that to add Axolotl one must install Pytorch as a prerequisite. Their installation instructions instruct one to run `pip3 install torch torchvision`. After running this, I ran their "Verification" steps and confirmed that torch was available to my Python 3.11 install. 

The axolotl instructions then instruct us to run `pip3 install -e .[flash-attn]`. This doesn't work in zsh (the current default shell for macOS, I believe?) because it uses globbing. For ZSH one has to run either `noglob pip3 install -e .[flash-attn]` or `pip3 install -e ".[flash-attn]"`. It would be nice if the docs explicitly mentioned this since zsh users are numerous in 2023. 

After surmounting that obstacle, the `pip3 install -e .[flash-attn]` command will begin to collect packages, but it stops at 
```
Collecting auto-gptq (from axolotl==0.3.0)
  Using cached auto_gptq-0.3.2.tar.gz (63 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/0n/tqjphhss68gb6blwrs34062c0000gn/T/pip-install-c3mbbl4v/auto-gptq_12704b62bacf46749c241bfba2ac79c0/setup.py", line 21, in <module>
          CUDA_VERSION = "".join(torch.version.cuda.split("."))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
In my first 30 minutes of Googling, there are no easy answers for how to resolve this. I presume this ticket will become the first Google result if it ends up having a Google-accessible URL. I'm at a loss for how to resolve this issue so far. I presume it has something to do with the arm64 architecture of my m2? Based on the log, it looks like perhaps the `auto-gptq` is expecting some library that is not always available after pip installing the `torch torchvision` packages.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by wbharding** [comment] 2023-09-17 15:48
Possibly relevant: https://github.com/PanQiWei/AutoGPTQ/issues/223

**Comment by tmm1** [comment] 2023-09-17 17:09
PyTorch does not work well on macOS. If you want to train models you will need CUDA compatible hardware and Linux

**Comment by NanoCode012** [comment] 2023-09-21 07:42
This is duplicate of #295 . I would recommend using linux platform instead while training for CUDA!

**Closed as completed by NanoCode012** 2023-09-21 07:42 UTC
