### ISSUE TITLE
Dolly prompt format

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#720] opened 2023-10-13 03:46 UTC
### What piece of documentation is affected?

datasets

### What part(s) of the article would you like to see updated?

I'd like to see how to use this dataset format which is 
question : context -> answer
i.e. the expectation is giving the model a question, the model will generate a context then answer

which isn't self explanatory until you see the url I posted

but I don't see that in the datasets format

I believe this is a closed book qa response, but I also see this style used by chatgpt.  Kind of like a chain of thought response.  When given a question, generates background context then an extractive (or abstractive) answer from the context.

### Additional Information

https://huggingface.co/datasets/lionelchg/dolly_closed_qa/viewer/default/train?row=0

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by thistleknot** [comment] 2023-10-13 03:52
note text
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/5154106/22df9fe5-1d98-4251-b1bc-97b1181f1ccb)

**Comment by NanoCode012** [comment] 2023-10-13 07:49
Please try the below.
```yml
  - path: repo
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: context
      field_output: response

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
```

**Comment by thistleknot** [comment] 2023-10-13 08:23
Supposed to be a yaml somewhere?

I also realized that

Maybe whoever wrote that format may have made an error and maybe the
initial dolly is setup just like cqa.

Else I could simply do a qa style and combine context and answer within a.

Either way this is great as a way for me to understand how to create my own
so thank you!

**Comment by thistleknot** [comment] 2023-10-13 09:57
NM I realized there is one yaml to rule them all

**Comment by thistleknot** [comment] 2023-10-13 10:06
I mis presumed alpaca was context, question, Answer but it's
Instruction, input... answer

Input is the same as closed book qa context

So I think I misstepped

**Comment by NanoCode012** [comment] 2023-10-16 05:26
Hello, did you manage to get it working?

**Comment by NanoCode012** [comment] 2023-10-22 15:57
Hey, I'll close this Issue for now. Please feel free to reopen if the issue is not solved.

**Closed as completed by NanoCode012** 2023-10-22 15:57 UTC

**Comment by thistleknot** [comment] 2023-10-22 16:07
yes I did.  I ensured my prompts had input, output, and instruction keys only and used the format you provided.
