### ISSUE TITLE
Mixtral 8Bit LoRA finetune with Zero-2: Linear8bitLt backward RuntimeError: size mismatch

### ISSUE THREAD

**Issue by hanoonaR** [axolotl-ai-cloud/axolotl#1236] opened 2024-01-31 21:08 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

When using `examples/mistral/mixtral.yml` with `load_in_8bit: true` - `Linear8bitLt` for backward propagation throws error, I expect the operation to complete without errors, similar to how it works with 4bit.

### Current behaviour

I'm encountering a RuntimeError indicating a size mismatch when attempting to use `Linear8bitLt` with backward propagation. This issue appears to be specific to the LoRA 8-bit training - while 4-bit works just fine.

### Steps to reproduce

`accelerate launch -m axolotl.cli.train examples/mistral/mixtral.yml --deepspeed deepspeed_configs/zero2.json` with `load_in_8bit: true`

### Config yaml

`examples/mistral/mixtral.yml` with `load_in_8bit: true`

### Possible solution

This issue seems similar to what was reported in the issue https://github.com/TimDettmers/bitsandbytes/issues/804 on the bitsandbytes. I would really appreciate any support. Thank you. 

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment] 2024-01-31 23:02
Duplicate of #953

**Closed as completed** 2024-02-01 01:27 UTC
Labels: bug

**Comment by hanoonaR** [comment] 2024-02-01 07:12
@winglian, 
 I came across the same issue - as in https://github.com/OpenAccess-AI-Collective/axolotl/issues/953
`RuntimeError: Output 0 of MatMul8bitLtBackward is a view and is being modified inplace.`, but solved it with peft update or this fix: https://github.com/huggingface/peft/pull/1372/files

However, I think the the issue I am facing is not related to peft:

```
Traceback (most recent call last):
  File "/home/demo.py", line 43, in <module>
    loss.backward()
  File "/home/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 485, in backward
    .mul_(state.SCB.unsqueeze(1).mul(1.0 / 127.0))
RuntimeError: The size of tensor a (32) must match the size of tensor b (8) at non-singleton dimension 0

```

Have you had any success in training 8-bit LoRA fine-tuning for Mixtral? Thank you.

**Comment by exhyy** [comment] 2024-11-15 02:04
hi @hanoonaR , I am facing the same error as yours, have you solved the problem? Thank you.
