### ISSUE TITLE
Problem with raw text completion training - possible issue with flash-attn

### ISSUE THREAD

**Issue by jaredquekjz** [axolotl-ai-cloud/axolotl#656] opened 2023-09-30 13:51 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Same qLoRA.yaml script. Training for raw text completion for same model should still start without any issue just like 2 days ago.

### Current behaviour

But after doing a git pull (c1382e7)- the training for raw text completion now trigger the following traceback just after training begins: 
```
  0%|                                                                                               | 0/18914 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/jaredquek/Python/axolotl/scripts/finetune.py", line 54, in <module>
    fire.Fire(do_cli)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jaredquek/Python/axolotl/scripts/finetune.py", line 50, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/jaredquek/Python/axolotl/src/axolotl/train.py", line 118, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jaredquek/Python/axolotl/src/axolotl/utils/trainer.py", line 310, in compute_loss
    return super().compute_loss(model, inputs, return_outputs=return_outputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/peft/peft_model.py", line 946, in forward
    return self.base_model(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1034, in forward
    outputs = self.model(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 917, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 913, in custom_forward
    return module(*inputs, past_key_value, output_attentions, padding_mask=padding_mask)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 631, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 489, in forward
    attn_output = self._flash_attention_forward(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 526, in _flash_attention_forward
    query_states, key_states, value_states, indices_q, cu_seq_lens, max_seq_lens = self._upad_input(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 562, in _upad_input
    query_layer.reshape(batch_size * kv_seq_len, num_heads, head_dim), indices_k
RuntimeError: shape '[2048, 8, 128]' is invalid for input of size 16777216

```

Think the problem, which never occurred before concerns the last few lines. Unfortunately even when I reverted to earlier pulls (3fbde76 HEAD@{3}: pull: Fast-forward
58cf7e7 HEAD@{4}: pull: Fast-forward) - it triggers another kind of error. This kind explicitly involving padding mask and flash-attn: 

```
  File "/home/jaredquek/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
TypeError: flashattn_forward() got an unexpected keyword argument 'padding_mask'
```

Any help appreciated. Has there been some breaking change in flash-attn library?

My qlora.yml (for text completion): 

```
base_model: /home/jaredquek/text-generation-webui/models/Olier
base_model_config: /home/jaredquek/text-generation-webui/models/Olier

model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true


load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/jaredquek/Python/Olier/DataProcessing/JSONS/combinedtext.jsonl
    type: completion
dataset_prepared_path: 
val_set_size: 0
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 500
sample_packing: false
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: 
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: huggingface
wandb_entity: singaporespprtsschool
wandb_watch:
wandb_run_id: QLoraAxolotlSep30Text
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 2
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.00001
train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false


gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 500
eval_steps: 
eval_table_size: 
save_steps: 2000
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

```
### Steps to reproduce

Use the above config to train a text-completion model. 

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/4d6490b

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jaredquekjz** [comment] 2023-10-01 06:39
Ok UPDATE (1 October): I tried the latest axolotl training with ShareGPT format - also got the same issue:
```

"  0%|                                                 | 0/48205 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jaredquek/Python/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jaredquek/Python/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/jaredquek/Python/axolotl/src/axolotl/train.py", line 118, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jaredquek/Python/axolotl/src/axolotl/utils/trainer.py", line 310, in compute_loss
    return super().compute_loss(model, inputs, return_outputs=return_outputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/peft/peft_model.py", line 946, in forward
    return self.base_model(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1034, in forward
    outputs = self.model(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 917, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 913, in custom_forward
    return module(*inputs, past_key_value, output_attentions, padding_mask=padding_mask)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 631, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jaredquek/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 489, in forward
    attn_output = self._flash_attention_forward(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 526, in _flash_attention_forward
    query_states, key_states, value_states, indices_q, cu_seq_lens, max_seq_lens = self._upad_input(
  File "/home/jaredquek/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 562, in _upad_input
    query_layer.reshape(batch_size * kv_seq_len, num_heads, head_dim), indices_k
RuntimeError: shape '[2816, 8, 128]' is invalid for input of size 23068672"""

```

**Comment by winglian** [comment] 2023-10-02 12:51
there's an off by one issue somewhere. I've seen this before. let me see if I can track down the previous issue

**Comment by winglian** [comment] 2023-10-02 12:53
try deleting the tokenized dataset (simply remove the `last_run_prepared` folder should suffice)

**Comment by jaredquekjz** [comment] 2023-10-03 13:26
Hmmm I tried deleting the last_run_prep folder and also left empty the dataset_prepared_path as u can see in the yml file on top. But to no avail. What might be causing this particular error?

**Comment by NanoCode012** [comment] 2023-10-04 08:03
May I ask if you have updated your transformer version to the latest axolotl branch?

Could you please help verify a few things?
1. Does enabling `sample_packing` fix this? Found this person having exact issue about a week ago https://discord.com/channels/1104757954588196865/1111279858136383509/1155936866005172375
2. Do the examples in the repo work for you as-is? It seems like the issue persist across completion and sharegpt?

**Comment by jaredquekjz** [comment] 2023-10-06 11:21
1. I managed to fix this issue by using the Docker containers...both sharegpt and text-completion work now. So it's probably an environmental issue. Thanks for ur attention.
2. Just to verify - does 'sample packing' means the dataset will be shuffled?

**Comment by NanoCode012** [comment] 2023-10-06 11:54
Nice to hear it is solved.

Sample packing: uses a multipacker algorithm that efficiently packs sequences together.

Is there another issue as I noticed you reopened the Issue?

**Comment by jaredquekjz** [comment] 2023-10-06 11:56
No further issue. I just wanted to ask about the sample packing. So it does not shuffle - but just pack the dataset - speeding training?

**Comment by NanoCode012** [comment] 2023-10-06 12:02
Yes, that's what it does from a general overview. Unfortunately, I do not understand the inner components myself. For a deeper explanation, it would be better to join the discord for clarification :)

**Comment by kallewoof** [comment] 2023-10-06 13:13
I have this issue, even with latest transformers (4.34.0.dev0). Enabling sample packing does make it go away, but that introduces a different issue that causes my loss to spike eventually.

**Comment by NanoCode012** [comment] 2023-10-06 13:18
Could you please provide stack trace and reproduce steps?

**Comment by kallewoof** [comment] 2023-10-06 13:24
Huh. It works now after I (again) upgraded transformers from 0.43.0.dev0 to 0.43.0.dev0, so nevermind I guess.

**Comment by NanoCode012** [comment] 2023-10-06 13:30
Oh nice. Sometimes I would completely uninstall transformers before installing from commit. pip is sometimes finicky. Closing this since it's now solved.

**Closed as completed by NanoCode012** 2023-10-06 13:30 UTC
Labels: bug
