### ISSUE TITLE
Error running docker image on Runpod

### ISSUE THREAD

**Issue by ssmi153** [axolotl-ai-cloud/axolotl#257] opened 2023-07-02 14:31 UTC
From yesterday, when I launch a new Axolotl docker image on Runpod, I get an error when I try to run the accelerate config command:

NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"

Is this perhaps related to the update you made to the base docker container?

Here's more of the stack trace:

`/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 132, in <module>
    from .launch import (
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/launch.py", line 27, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/other.py", line 30, in <module>
    from deepspeed import DeepSpeedEngine
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 112, in collect_model_fields
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-req-build-6e9pv52m
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-6e9pv52m
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from peft==0.4.0.dev0) (5.9.5)
Requirement already satisfied: transformers in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from peft==0.4.0.dev0) (4.31.0.dev0)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from torch>=1.13.0->peft==0.4.0.dev0) (3.12.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from torch>=1.13.0->peft==0.4.0.dev0)
) (11.7.99)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from torch>=1.13.0->peft==0.4.0.dev0) (
Requirement already satisfied: fsspec in /root/miniconda3/envs/py3.9/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers->peft==0.4.0.de
Wa6ebqvaAibZaMdL30R+qQLuGcxJE6NZ9LQ/nVcgAAAJgYDo1fGA6N\nXwAAAAtzc2gtZWQyNTUxOQAAACCCtQWa6ebqvaAibZaMdL30R+qQLuGcxJE6NZ9LQ/nVcg\nAAAEDK5Q4+gjbdnZci0rJzh81LbVu5Lwm
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 132, in <module>
    from .launch import (
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/launch.py", line 27, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/utils/other.py", line 30, in <module>
    from deepspeed import DeepSpeedEngine
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 792, in <module>
    from ..pipe import PipelineModule
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 26, in <module>
    from deepspeed.runtime.zero.config import DeepSpeedZeroConfig
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/runtime/zero/config.py", line 79, in <module>
    class DeepSpeedZeroConfig(DeepSpeedConfigModel):
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 112, in collect_model_fields
    raise NameError(f'Field "{ann_name}" has conflict with protected namespace "{protected_namespace}"')
NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"`

**Comment by NanoCode012** [comment] 2023-07-02 14:35
Could you provide the command and steps to reproduce?

**Comment by ssmi153** [comment] 2023-07-03 01:00
OK. I'm running the axolotl runpod docker image (winglian/axolotl-runpod:main-py3.9-cu118-2.0.0) on a runpod A100 80GB pod. No special startup commands in the pod configuration - just the vanilla docker image.

Once the docker image has loaded I connect to the web terminal and run the following commands (as per your documentation):

`cd /workspace/axolotl
pip3 install -e .
pip3 install -U git+https://github.com/huggingface/peft.git

accelerate config
`

I'm getting this error when I run these commands. This process worked up until 2-3 days ago.

**Comment by NanoCode012** [comment] 2023-07-03 01:12
Following this message log, it's due to pydantic

https://discord.com/channels/1104757954588196865/1111279858136383509/1125169872154923230

A PR will be in the works later.

For now, you can workaround using `pip install pydantic==v1.10.10`

Please do tell if this fixed it for you

**Comment by ssmi153** [comment] 2023-07-03 02:46
Great, that seemed to work. For anyone else, that turns the sequence of commands into:

```
cd /workspace/axolotl
pip3 install -e .
pip3 install -U git+https://github.com/huggingface/peft.git

pip3 install pydantic==v1.10.10

accelerate config
```

which seems to do the trick.

**Closed as completed** 2023-07-03 02:46 UTC
